name: ✨ Request a feature
description: Request a new feature to implement in Pi Support
title: "[Request]"
labels:
  - request
  - triage
body:
  - type: markdown
    attributes:
      value: >
        **Thank you for wanting to request a feature in Pi Support!**
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Eg, "I'm always frustrated when [...]".
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context, file uploads and/or screenshots about the feature request here.
